pipeline{
    agent any
    stages{
        stage('checkout scm'){
            steps{
                checkout scm
            }
        }
        stage('Build'){
            steps{
                echo "Building application"
            }
        }
        stage('Test'){
            steps{
                sh 'python3 scanrio5_meraz/app.py'
            }
        }
    }
    post{
        success{
            echo "Build success"
        }
        failure{
            echo "Build failed"
        }
    }
}