pipeline{
    agent any
    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }
        stage('Build python script'){
            steps{
                sh 'python3 app.py'
            }
        }
    }
    post{
        success{
            echo "Python script run sucessfully"
        }
        failure{
            echo "Python script failed"
        }
    }
}